[SetNames]
!setname 0x3939 Vocaloid

!39393939
0 Add 1 "Vocaloid" card from your Deck to your hand.
1 (Quick Effect): You can discard 1 card; Special Summon 1 "Vocaloid" monster from your hand, also you cannot Special Summon monsters for the rest of this turn, except "Vocaloid" monsters.